#!/usr/bin/env python3
"""dnsmasq DHCP support"""
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

import sys
import logging
import datetime
import socket

from pathlib import Path

import phoenix
from phoenix.system import System
from phoenix.network import Network
from phoenix.node import Node

from jinja2 import Template
from jinja2.exceptions import TemplateSyntaxError
from jinja2 import ChoiceLoader, FileSystemLoader, PackageLoader
from jinja2 import Environment

def _escape_vendorclass(vendorclass):
    table = str.maketrans({' ': '_', '/': '_', '\\': '_'})
    return vendorclass.translate(table)

class DnsmasqDhcp(object):
    dhcptype = "dnsmasq"
    environment = None

    @classmethod
    def update_dhcp_reservations(cls):
        leasetime='10m'
        curtime = datetime.datetime.now()
        timestamp = curtime.strftime('%Y-%m-%d %H:%M:%S')
        output = [ '# this file was generated by Phoenix at %s' % timestamp ]
        for nodename,node in sorted(Node.nodes.items()):
            if 'interfaces' not in node:
                continue
            for ifacename, iface in node['interfaces'].items():
                if 'dhcp' not in iface:
                    continue
                if 'ip' not in iface or iface['ip'] == None:
                    logging.warn("No IP defined for %s interface %s", nodename, ifacename)
                    continue
                if 'hostname' in iface:
                    hostname = iface['hostname']
                elif 'primary' in iface and iface['primary']:
                    hostname = nodename
                else:
                    hostname = '%s-%s' % (nodename, ifacename)
                if 'discoverytype' in iface and iface['discoverytype'] == 'dhcp':
                    if 'switch' not in iface:
                        logging.warn("No switch defined for %s interface %s", nodename, ifacename)
                        continue
                    if 'switchport' not in iface:
                        logging.warn("No switchport defined for %s interface %s", nodename, ifacename)
                        continue
                    elements = ["*:*:*:*:*:*"]
                    elements.append('tag:' + iface['switch'])
                    elements.append('tag:' + iface['switchport'])
                    if 'vendorclass' in iface:
                        elements.append('tag:' + _escape_vendorclass(iface['vendorclass']))
                    elements.append(iface['ip'])
                    elements.append(hostname)
                    elements.append(leasetime)
                    output.append(','.join(elements))
                else:
                    if 'mac' not in iface or iface['mac'] is None or iface['mac'] == 'None':
                        logging.warn("No MAC address for %s interface %s", nodename, ifacename)
                        continue
                    output.append("%s,%s,%s,%s" % (iface['mac'], iface['ip'], hostname, leasetime))
        try:
            outputfile = '/etc/dnsmasq.hosts.d/phoenix.conf'
            with open(outputfile, 'w') as ethersfile:
                ethersfile.write('\n'.join(output))
                ethersfile.write('\n')
        except:
            logging.error("Could not write to %s", outputfile)
            return(False)

        return("Ok")

    @classmethod
    def load_environment(cls):
        if cls.environment is not None:
            return

        cls.environment = Environment()
        cls.environment.loader = ChoiceLoader([
            FileSystemLoader([Path(phoenix.conf_path) / 'templates']),
            PackageLoader('phoenix', 'templates')
        ])

    @classmethod
    def get_dhcp_conf(cls):
        cls.load_environment()
        Network.load_config()
        template = cls.environment.get_template('dnsmasq.conf.j2')

        if 'dnsmasq' in System.config:
            settings = System.config['dnsmasq']
        else:
            settings = {}

        local_ip = socket.gethostbyname(socket.gethostname())

        return template.render({
            'System': System.config,
            'Network': Network.config,
            'Dnsmasq': settings,
            'Ip': local_ip,
            })
