#!/usr/bin/env python3
"""dnsmasq DHCP support"""
# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

import sys
import logging
import datetime
import phoenix
from phoenix.system import System
from phoenix.node import Node

class DnsmasqDhcp(object):
    dhcptype = "dnsmasq"

    @classmethod
    def update_dhcp_reservations(cls):
        curtime = datetime.datetime.now()
        timestamp = curtime.strftime('%Y-%m-%d %H:%M:%S')
        output = [ '# this file was generated by Phoenix at %s' % timestamp ]
        for nodename,node in sorted(Node.nodes.items()):
            if 'interfaces' not in node:
                continue
            for ifacename, iface in node['interfaces'].items():
                if 'dhcp' not in iface:
                    continue
                if 'ip' not in iface or iface['ip'] == None:
                    logging.warn("No IP defined for %s interface %s", nodename, ifacename)
                    continue
                hostname = iface['hostname'] if 'hostname' in iface else '%s-%s' % (nodename, ifacename)
                if 'discoverytype' in iface and iface['discoverytype'] == 'dhcp':
                    if 'switch' not in iface:
                        logging.warn("No switch defined for %s interface %s", nodename, ifacename)
                        continue
                    if 'switchport' not in iface:
                        logging.warn("No switchport defined for %s interface %s", nodename, ifacename)
                        continue
                    output.append("*:*:*:*:*:*,tag:%s,tag:port%s,%s,%s,10m" % (iface['switch'], iface['switchport'], iface['ip'], hostname))
                else:
                    if 'mac' not in iface or iface['mac'] is None or iface['mac'] == 'None':
                        logging.warn("No MAC address for %s interface %s", nodename, ifacename)
                        continue
                    output.append("%s,%s,%s,10m" % (iface['mac'], iface['ip'], hostname))
        try:
            outputfile = '/etc/dnsmasq.hosts.d/phoenix.conf'
            with open(outputfile, 'w') as ethersfile:
                ethersfile.write('\n'.join(output))
                ethersfile.write('\n')
        except:
            logging.Error("Could not write to %s", outputfile)
            return(False)

        return("Ok")

    @classmethod
    def get_dhcp_conf(cls):
        return "# not yet implemented"
